name: Deploy-AI
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Inject
        run: sed -i "s@__API_KEY_PLACEHOLDER__@${{ secrets.GEMINI_API_KEY }}@g" main.js
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy
        uses: actions/deploy-pages@v4
